config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'categories#index'
  
  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  #validates :title, presence: true
  has_many :product_categories
  has_many :categories, through: :product_categories
  
  has_many :variants, class_name: 'ProductVariant'
end
 

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ActionController::Base
    def index
        @categories = Category.joins(:products).select('categories.*, count(products.id) as products_count').group('categories.id').order(:title)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   def index
       @category = Category.find(params[:category_id])
       @products = @category.products.includes(:variants).order(:title)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h2>Categories (<%= @categories.length %>)</h2>

<ol>
    <% @categories.each do |category| %>
    <li>
        <%= link_to category_products_path(category) do %>
        <%= category.title %>
        (<%= category.products_count %>)
        <% end %>
        
    </li>
    <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2>
  <%= link_to "Categories", root_path %> /
  <%= @category.title %> /
  Products
</h2>

<ol>
  <% @products.each do |product| %>
    <li>
      <%= product.title %> (<%= number_to_currency product.price %>)

      <%= form_tag order_items_path do %>
        <%= hidden_field_tag :product_id, product.id %>
        <%= number_field_tag :quantity, 1 %>
        <%= submit_tag "Add to Cart" %>
      <% end %>

      <ul>
        <% product.variants.each do |variant| %>
          <li><%= variant.title %> (<%= number_to_currency variant.price %>)</li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ol>